server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/db.liquibase/master.xml
    enabled: ${LIQUIBASE_ENABLED:false}
    contexts: local

  application:
    name: "<< Weather >>"
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/weather
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
jwt:
  token:
    secret: jwtjavasamo
    validity: 864000000
springdoc:
  swagger-ui:
    path: /v1/swagger/index.html
  api-docs:
    path: /v1/swagger/api-docs